# Generated by Django 2.2.3 on 2019-08-20 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20190813_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='New Announcement', max_length=100)),
                ('body', models.TextField()),
                ('display', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error'), ('success', 'Success'), ('info', 'Info')], default='info', max_length=7)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Announcer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
