# Generated by Django 2.2.3 on 2019-08-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190820_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.AlterField(
            model_name='announcement',
            name='level',
            field=models.CharField(choices=[('warning', 'Warning. Be careful!'), ('error', 'Error. Fix it!'), ('success', 'Success. Let is celebrate!'), ('info', 'Information. No action required!'), ('danger', 'Danger. We are stuffed!')], default='info', max_length=7),
        ),
    ]
